#!/bin/bash

VERSION=0.3
# WEB_URL="http://softlayer-dal.dl.sourceforge.net/project/$BM_NAME/$BM_NAME/${VERSION}/${BM_NAME}-${VERSION}.tar.gz"
WEB_URL="http://nfssv.rhts.fuchu/export/data/user/n-horiguchi/mmtests-mirror/ebizzy-0.3.tar.gz"

install()
{
	cp -af $BM_NAME $BM_ROOT
}
