#!/bin/bash

download()
{
	# Fuchu beaker specific setting
	[ ! -d /mnt/src ] && mkdir -p /mnt/src
	mount nfssv.rhts.fuchu:/export /mnt/src
	if [ $? -eq 0 ] ; then
		echo "git --git-dir=/mnt/src/data/user/n-horiguchi/lkp-tests-mirror/rt-tests.git/.git show HEAD:src/hackbench/hackbench.c > hackbench.c"
		git --git-dir=/mnt/src/data/user/n-horiguchi/lkp-tests-mirror/rt-tests.git/.git show HEAD:src/hackbench/hackbench.c > hackbench.c
		umount -f /mnt/src
		return
	else
		wget -O hackbench.c https://raw.githubusercontent.com/jlelli/rt-tests/master/src/hackbench/hackbench.c
	fi
}

build()
{
	gcc -g -Wall -O2 -o hackbench hackbench.c -lpthread
}

install()
{
	/usr/bin/install hackbench /usr/bin/hackbench
}
